USE psms;
-- Staff
ALTER TABLE Staff 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- FIR
ALTER TABLE FIR 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ArrestRegister
ALTER TABLE ArrestRegister 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ChallanRegister
ALTER TABLE ChallanRegister 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- WantedCriminals
ALTER TABLE WantedCriminals 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- DutyRoster
ALTER TABLE DutyRoster 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Beat
ALTER TABLE Beat 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- BeatBook
ALTER TABLE BeatBook 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- GovtAssets
ALTER TABLE GovtAssets 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- RecoveredProperty
ALTER TABLE RecoveredProperty 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- SearchOperation
ALTER TABLE SearchOperation 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Surveillance
ALTER TABLE Surveillance 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- GovtFund
ALTER TABLE GovtFund 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- FundUsage
ALTER TABLE FundUsage 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- OfficialCorrespondence
ALTER TABLE OfficialCorrespondence 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- InspectionRegister
ALTER TABLE InspectionRegister 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Roznamcha
ALTER TABLE Roznamcha 
ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;